import streamlit as st
import json
import random

# --------------------------------------------------------------------------
# CONFIGURATION & STYLE
# --------------------------------------------------------------------------
st.set_page_config(page_title="Clinical AI Trainer", layout="wide")

# === DISCLAIMER ===
st.warning("""
**⚠️ PROTOTYPE VERSION (v0.9)**
* **Purpose:** Logic validation and content safety review.
* **Instruction:** Focus on evaluating the *Clinical Accuracy* and *Safety Logic*.
""")

# Custom CSS - Tweaked for better visibility
st.markdown("""
<style>
    /* Patient Box - Stronger Blue */
    .patient-box {
        background-color: #e3f2fd;
        padding: 20px;
        border-radius: 10px;
        border-left: 8px solid #0d47a1;
        margin-bottom: 20px;
        font-family: sans-serif;
        font-size: 1.1em;
    }
    .patient-label {
        font-weight: bold;
        color: #0d47a1;
        margin-bottom: 8px;
        text-transform: uppercase;
        font-size: 0.9em;
        letter-spacing: 1px;
    }
    
    /* AI Box - Stronger Green */
    .ai-box {
        background-color: #f1f8e9;
        padding: 20px;
        border-radius: 10px;
        border-left: 8px solid #2e7d32;
        margin-bottom: 25px;
        font-family: monospace;
        font-size: 1.05em;
    }
    .ai-label {
        font-weight: bold;
        color: #1b5e20;
        margin-bottom: 8px;
        text-transform: uppercase;
        font-size: 0.9em;
        letter-spacing: 1px;
    }

    /* Feedback Styling - High Contrast */
    .feedback-correct {
        background-color: #d4edda;
        color: #0f5132;
        padding: 20px;
        border-radius: 8px;
        margin-top: 15px;
        border: 2px solid #badbcc;
    }
    .feedback-incorrect {
        background-color: #f8d7da;
        color: #842029;
        padding: 20px;
        border-radius: 8px;
        margin-top: 15px;
        border: 2px solid #f5c2c7;
    }
    
    /* Button Styling overrides */
    div.stButton > button {
        width: 100%;
        height: 3em;
        font-weight: bold;
    }
</style>
""", unsafe_allow_html=True)

# --------------------------------------------------------------------------
# INSTRUCTIONS TEXT (Embedded)
# --------------------------------------------------------------------------
USER_GUIDE_TEXT = """
### Quick Start Guide

**1. Pick a Module (Top Left)**
* Look for the dropdown menu on the **Left Side** of the screen.
* **Select any module that interests you.**
* You do **not** need to go in order.
* *Tip: If you are new, we recommend starting with "Orientation".*

**2. Review the Lesson**
* Click the **"📖 Study Material"** tab at the top.
* Read the **Learning Objectives** for the module you selected.
* **Why?** You need to know the specific safety rules and boundaries taught in this lesson *before* you can evaluate the AI.

**3. Read the Case**
* Click the **"✍️ Simulation"** tab to switch to the exercises.
* **Blue Box:** This is the **User** sharing a concern.
* **Green Box:** This is the **AI Model Response** generated by the system.

**4. Evaluate Against Learning Objectives**
* **Your Task:** Determine if the AI’s response met the specific goals you just read in the Study Material.
* *Example:* If you selected the **Suicide Risk** module, did the AI follow the safety protocols for suicide risk? Did it stay within the boundaries of an AI (not acting as a doctor)?
* Select the option below that best matches your judgment.

**5. Check Your Mastery**
The system will immediately tell you if your assessment was correct:
* **✅ Correct:** You correctly identified whether the AI met or failed the learning objective.
* **❌ Incorrect:** You missed a critical error or misapplied the lesson's standard.

**6. Next Steps**
* Click **"Next Case"** to continue.
* If you want a fresh set of questions **for the module you are currently in**, click **"🔄 Restart Module"** on the left.
"""

# --------------------------------------------------------------------------
# DATA LOADING
# --------------------------------------------------------------------------
def load_data():
    try:
        with open('course_data.json', 'r', encoding='utf-8') as f:
            data = json.load(f)
        return data.get('modules', {})
    except (FileNotFoundError, json.JSONDecodeError):
        st.error("Error: course_data.json not found or invalid.")
        return {}

all_modules = load_data()

# --------------------------------------------------------------------------
# SESSION STATE MANAGEMENT
# --------------------------------------------------------------------------
if 'current_quiz' not in st.session_state:
    st.session_state['current_quiz'] = []
if 'quiz_index' not in st.session_state:
    st.session_state['quiz_index'] = 0
if 'selected_module_state' not in st.session_state:
    st.session_state['selected_module_state'] = None

def initialize_quiz(module_name):
    if module_name not in all_modules:
        st.session_state['current_quiz'] = []
        return

    raw_questions = all_modules[module_name].get('questions', [])
    if not raw_questions:
        st.session_state['current_quiz'] = []
        return

    # Pick Random 5
    selected_questions = random.sample(raw_questions, min(len(raw_questions), 5))
    
    quiz_session = []
    for q in selected_questions:
        q_copy = q.copy()
        q_copy['shuffled_options'] = random.sample(q['options'], len(q['options']))
        quiz_session.append(q_copy)
    
    st.session_state['current_quiz'] = quiz_session
    st.session_state['quiz_index'] = 0

# --------------------------------------------------------------------------
# SIDEBAR
# --------------------------------------------------------------------------
st.sidebar.title("🩺 Clinical AI Trainer")
st.sidebar.markdown("---")

if all_modules:
    module_names = list(all_modules.keys())
else:
    module_names = ["No Data Loaded"]

selected_module = st.sidebar.selectbox("Select Module", module_names)

if selected_module != st.session_state['selected_module_state']:
    initialize_quiz(selected_module)
    st.session_state['selected_module_state'] = selected_module
    st.rerun()

if st.sidebar.button("🔄 Restart Module"):
    initialize_quiz(selected_module)
    st.rerun()

# --------------------------------------------------------------------------
# MAIN CONTENT
# --------------------------------------------------------------------------
st.title(f"Module: {selected_module}")

# Create THREE Tabs
tab1, tab2, tab3 = st.tabs(["📖 Study Material", "✍️ Simulation", "ℹ️ User Guide"])

# --- TAB 1: STUDY MATERIAL ---
with tab1:
    if selected_module in all_modules:
        st.markdown(all_modules[selected_module].get('learning_content', "No content."))
    else:
        st.warning("Module content not found.")

# --- TAB 2: SIMULATION ---
with tab2:
    quiz_data = st.session_state['current_quiz']
    
    if not quiz_data:
        st.info("No questions available for this module.")
    else:
        idx = st.session_state['quiz_index']
        total = len(quiz_data)
        question = quiz_data[idx]
        
        progress_val = (idx + 1) / total
        st.progress(progress_val)
        st.caption(f"Question {idx + 1} of {total}")
        
        # 1. DISPLAY PATIENT
        st.markdown(f"""
        <div class="patient-box">
            <div class="patient-label">Patient Prompt</div>
            {question['user_prompt']}
        </div>
        """, unsafe_allow_html=True)
        
        # 2. DISPLAY AI
        st.markdown(f"""
        <div class="ai-box">
            <div class="ai-label">AI System Response</div>
            {question['ai_response']}
        </div>
        """, unsafe_allow_html=True)
        
        # 3. INTERACTION
        st.markdown("### Evaluate Against Learning Objectives")
        st.write("Does the AI response meet the specific goals taught in this module?")
        
        options_list = question['shuffled_options']
        options_text = [opt['text'] for opt in options_list]
        
        radio_key = f"q_{question['id']}_idx_{idx}"
        
        user_choice = st.radio(
            "Select assessment:",
            options_text,
            key=radio_key,
            index=None
        )
        
        # 4. FEEDBACK
        if user_choice:
            selected_option = next((opt for opt in options_list if opt['text'] == user_choice), None)
            if selected_option:
                if selected_option['is_correct']:
                    st.markdown(f"""
                    <div class="feedback-correct">
                        <h3>✅ Correct</h3>
                        {selected_option['feedback']}
                    </div>
                    """, unsafe_allow_html=True)
                else:
                    st.markdown(f"""
                    <div class="feedback-incorrect">
                        <h3>❌ Incorrect</h3>
                        {selected_option['feedback']}
                    </div>
                    """, unsafe_allow_html=True)

        st.markdown("---")
        
        # 5. NAVIGATION
        col_prev, col_next = st.columns([1, 1])
        
        with col_prev:
            if idx > 0:
                if st.button("⬅️ Previous Case"):
                    st.session_state['quiz_index'] -= 1
                    st.rerun()
                    
        with col_next:
            if idx < total - 1:
                if st.button("Next Case ➡️"):
                    st.session_state['quiz_index'] += 1
                    st.rerun()
            else:
                if st.button("🏁 Finish Module"):
                    st.success("You have completed all questions in this set!")

# --- TAB 3: USER GUIDE (Embedded) ---
with tab3:
    st.markdown(USER_GUIDE_TEXT)